nodes = [
  { :hostname => 'apt-repo-test',
    :ip => '172.16.56.50'
  },
]

required_plugins = %w(vagrant-hostmanager vagrant-vbguest)
plugins_to_install = required_plugins.select { |plugin| not Vagrant.has_plugin? plugin }
if not plugins_to_install.empty?
  puts "Installing plugins: #{plugins_to_install.join(' ')}"
  if system "vagrant plugin install #{plugins_to_install.join(' ')}"
    exec "vagrant #{ARGV.join(' ')}"
  else
    abort "Installation of one or more plugins has failed. Aborting."
  end
end

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.vm.box_check_update = false
  config.ssh.forward_agent = true

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  nodes.each do |node|
    config.vm.define node[:hostname] do |node_config|
      node_config.vm.host_name = node[:hostname] + '.vagrant'
      node_config.vm.network :private_network, ip: node[:ip]

      node_config.vm.provider :virtualbox do |vb|
        vb.memory = 2048
        vb.cpus = 1
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        vb.customize ["guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000]
      end
    end
  end
end
